# Generated by Django 4.1.7 on 2023-03-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activechallenge',
            old_name='challenge_date',
            new_name='date',
        ),
    ]
