# Generated by Django 4.1.7 on 2023-03-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='challenge_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='activechallenge',
            name='challenge_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='challenge_date',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='submission_username',
        ),
        migrations.AddField(
            model_name='activechallenge',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectGreen.challenge'),
        ),
        migrations.AddField(
            model_name='submission',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectGreen.challenge'),
        ),
        migrations.AddField(
            model_name='upvote',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectGreen.submission'),
        ),
        migrations.AlterField(
            model_name='activechallenge',
            name='challenge_date',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Challenge Date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='minutes_late',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='submission',
            table='Submissions',
        ),
        migrations.AlterModelTable(
            name='upvote',
            table='Upvotes',
        ),
    ]
