# Generated by Django 4.1.7 on 2023-03-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reported_by',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_false_reports',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='reported_by',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
