# Generated by Django 4.1.7 on 2023-03-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0002_comment_reported_by_profile_number_of_false_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='allowed_distance',
            field=models.DecimalField(decimal_places=15, default=999999.9, max_digits=22),
        ),
        migrations.AddField(
            model_name='challenge',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='challenge',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=18),
        ),
    ]
