# Generated by Django 4.1.7 on 2023-03-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0002_comment_reported_by_profile_number_of_false_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='sum_of_interactions',
            field=models.FloatField(default=0.0),
        ),
    ]
