# Generated by Django 4.1.7 on 2023-03-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0003_challenge_allowed_distance_challenge_latitude_and_more'),
        ('projectGreen', '0003_submission_sum_of_interactions'),
    ]

    operations = [
    ]
