# Generated by Django 4.1.7 on 2023-03-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0003_rename_challenge_submission_active_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_username', models.CharField(max_length=20)),
                ('right_username', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Friends',
            },
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
