# Generated by Django 4.1.7 on 2023-03-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0004_merge_20230317_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='allowed_distance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reported_by',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='reported_by',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
