# Generated by Django 4.1.6 on 2023-03-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0004_merge_20230317_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=256)),
                ('cost', models.IntegerField(default=0)),
                ('item_bytes', models.BinaryField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='challenge',
            name='allowed_distance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
    ]
