# Generated by Django 4.1.7 on 2023-03-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0005_submission_reported_submission_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='photo_bytes',
            field=models.BinaryField(null=True),
        ),
    ]
