# Generated by Django 4.1.6 on 2023-03-19 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0005_owneditems_store_alter_challenge_allowed_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='item_bytes',
        ),
    ]
