# Generated by Django 4.1.7 on 2023-03-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0005_alter_challenge_allowed_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='lambda_user',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='upvote',
            name='lambda_user',
            field=models.FloatField(default=0.0),
        ),
    ]
