# Generated by Django 4.1.7 on 2023-03-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0006_submission_photo_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_submissions_removed',
            field=models.IntegerField(default=0),
        ),
    ]
