# Generated by Django 4.1.6 on 2023-03-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0006_remove_store_item_bytes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OwnedItems',
            new_name='OwnedItem',
        ),
        migrations.RenameModel(
            old_name='Store',
            new_name='StoreItem',
        ),
        migrations.AlterModelTable(
            name='owneditem',
            table='OwnedItems',
        ),
        migrations.AlterModelTable(
            name='storeitem',
            table='StoreItems',
        ),
    ]
