# Generated by Django 4.1.7 on 2023-03-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0006_comment_lambda_user_upvote_lambda_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='Comments',
        ),
    ]
