# Generated by Django 4.1.7 on 2023-03-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0007_friend_pending_profile_number_of_submissions_removed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='minutes_late',
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_time',
            field=models.DateTimeField(null=True, verbose_name='Submission Time'),
        ),
    ]
