# Generated by Django 4.1.7 on 2023-03-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0007_alter_comment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribed_to_emails',
            field=models.BooleanField(default=True),
        ),
    ]
