# Generated by Django 4.1.6 on 2023-03-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0007_rename_owneditems_owneditem_rename_store_storeitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='spendable_points',
            field=models.IntegerField(default=0),
        ),
    ]
