# Generated by Django 4.1.6 on 2023-03-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0008_profile_spendable_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='item_bytes',
            field=models.BinaryField(null=True),
        ),
    ]
