# Generated by Django 4.1.6 on 2023-03-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0010_rename_item_bytes_storeitem_photo_bytes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='photo_bytes',
        ),
        migrations.AddField(
            model_name='storeitem',
            name='photo',
            field=models.ImageField(default='/static/img/Post1.jpg', upload_to='storePhotos'),
            preserve_default=False,
        ),
    ]
