# Generated by Django 4.1.6 on 2023-03-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0012_alter_storeitem_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='photo',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
