# Generated by Django 4.1.7 on 2023-03-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0013_alter_storeitem_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='text_colour',
            field=models.CharField(default='FFFFFF', max_length=6),
        ),
    ]
