# Generated by Django 4.1.7 on 2023-03-22 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0008_profile_subscribed_to_emails'),
        ('projectGreen', '0014_storeitem_text_colour'),
    ]

    operations = [
    ]
