# Generated by Django 4.1.7 on 2023-03-22 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0015_merge_20230322_0001'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='owneditem',
            table='Comments',
        ),
    ]
