# Generated by Django 4.1.7 on 2023-03-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0016_alter_comment_table_alter_owneditem_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='Comments',
        ),
        migrations.AlterModelTable(
            name='owneditem',
            table='OwnedItems',
        ),
    ]
