# Generated by Django 4.1.7 on 2023-03-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectGreen', '0017_alter_comment_table_alter_owneditem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blank',
            field=models.FloatField(default=0.0),
        ),
    ]
