name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    matrix:
      runs-on: [ubuntu-latest, macos-latest, windows-latest]
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    runs-on: ${{ matrix.runs-on }}
  
  steps:
  - uses: actions/checkout@v3
  - name: Set up Python ${{ matrix.python-version }}
    uses: actions/setup-python@v3
    with:
      python-version: ${{ matrix.python-version }}
  - name: Install Dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r .\djangoApp\projectGreen\requirements.txt
  - name: Run Unit Tests
    run: |
      cd imageMetadata
      python -m pytest