name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

runs-on: ubuntu-latest
  strategy:
    max-parallel: 4
    matrix:
      python-version: [3.9]

jobs:
  build:
  - uses: actions/checkout@v3
  - name: Set up Python ${{ matrix.python-version }}
    uses: actions/setup-python@v3
    with:
      python-version: ${{ matrix.python-version }}
  - name: Install Dependencies
    run: |
      cd djangoApp\projectGreen
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      cd ..
      cd ..
  - name: Run Unit Tests
    run: |
      cd imageMetadata
      python -m pytest